package_rename_config:
  android:
    app_name: "패럿패럿"
    package_name: "com.tlabs.parot"
    override_old_package: # (Optional) (String) Use this to delete the old folder structure of MainActivity or to use the existing code with the new package name
    lang: # (Optional) (String) The android development language {kotlin(default) or java}

  ios:
    app_name: "패럿패럿"
    bundle_name: "com.tlabs.parot"
    package_name: "com.tlabs.parot"

  web:
    app_name: "패럿패럿"
    description: # (String) The description of the web app and PWA
